# coding: utf-8

debit_occurrences = {
    '101': 'Cheque Compensado',
    '102': 'Encargos',
    '103': 'Estornos',
    '104': 'Lançamento Avisado',
    '105': 'Tarifas',
    '106': 'Aplicação',
    '107': 'Empréstimo / Financiamento',
    '108': 'Câmbio',
    '109': 'CPMF',
    '110': 'IOF',
    '111': 'Imposto de Renda',
    '112': 'Pagamento Fornecedores',
    '113': 'Pagamentos Salário',
    '114': 'Saque Eletrônico',
    '115': 'Ações',
    '117': 'Transferência entre Contas',
    '118': 'Devolução da Compensação',
    '119': 'Devolução de Cheque Depositado',
    '120': 'Transferência Interbancária (DOC, TED)',
    '121': 'Antecipação a Fornecedores',
    '122': 'OC / AEROPS',
    '123': 'Saque em Espécie',
    '124': 'Cheque Pago',
    '125': 'Pagamentos Diversos',
    '126': 'Pagamento de Tributos',
    '127': 'Cartão de crédito - Pagamento de fatura de cartão de crédito da própria IF',
}

credit_occurrences = {
    '201': 'Depósito em Cheque',
    '202': 'Crédito de Cobrança',
    '203': 'Devolução de Cheques',
    '204': 'Estornos',
    '205': 'Lançamento Avisado',
    '206': 'Resgate de Aplicação',
    '207': 'Empréstimo / Financiamento',
    '208': 'Câmbio',
    '209': 'Transferência Interbancária (DOC, TED)',
    '210': 'Ações',
    '211': 'Dividendos',
    '212': 'Seguro',
    '213': 'Transferência entre Contas',
    '214': 'Depósitos Especiais',
    '215': 'Devolução da Compensação',
    '216': 'OCT',
    '217': 'Pagamentos Fornecedores',
    '218': 'Pagamentos Diversos',
    '219': 'Recebimento de Salário',
    '220': 'Depósito em Espécie',
    '221': 'Pagamento de Tributos',
    '222': 'Cartão de Crédito - Recebíveis de cartão de crédito',
}
